import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "submit records",
  description: "submit records Generated by next-14",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body >{children}</body>
    </html>
  );
}
